sudo: required

services:
  - docker

env:
  global:
    CACHE_IMAGE: java:8
    DOCKER_IMAGE: carlositline/thot-siwa

before_script:
  - docker pull $CACHE_IMAGE || true
  - case $TRAVIS_BRANCH in master) project=latest;; default) project=$TRAVIS_BRANCH;; esac

script:
  - docker build --tag $DOCKER_IMAGE:$project "."

after_success:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker push $DOCKER_IMAGE:$project